version: "3"

services:
  nest:
    image: node:19.0.0-alpine
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node

  nest_db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/data/db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db: