version: '3.8'

services:
  temporal-service:
    image: node:19.0.0-alpine
    container_name: temporal-service
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./temporal-service:/home/node

  temporal-service-db:
    image: postgres:15.2
    container_name: temporal-service-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/data/db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db: