version: '3.8'

services:
  gateway-service:
    extends:
      file: ./gateway-service/docker-compose.yaml
      service: gateway-service

  user-service:
    extends:
      file: ./user-service/docker-compose.yaml
      service: user-service

  user-service-db:
    extends:
      file: ./user-service/docker-compose.yaml
      service: user-service-db

  auth-service:
    extends:
      file: ./auth-service/docker-compose.yaml
      service: auth-service

  auth-service-db:
    extends:
      file: ./auth-service/docker-compose.yaml
      service: auth-service-db
      
volumes:

  auth-db:

  user-db:

networks:
  default:
    name: microservices-network
