# auth-service
version: '3.8'

services:
  auth-service:
    image: node:19.0.0-alpine
    container_name: auth-service
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    env_file:
      - .auth-service.env
    ports:
      - "3002:3000"
    volumes:
      - .:/home/node
      - ../libs:/home/node/libs

  auth-service-db:
    image: postgres:15-alpine3.16
    container_name: auth-service-db
    restart: always
    env_file:
      - .auth-service.env
    environment:
      POSTGRES_PASSWORD: ${AUTH_SERVICE_PASSWORD}
      POSTGRES_HOST: ${AUTH_SERVICE_HOST}
      POSTGRES_PORT: ${AUTH_SERVICE_PORT}
      POSTGRES_USER: ${AUTH_SERVICE_USER}
      POSTGRES_DB: ${AUTH_SERVICE_DB}
    ports:
      - "5432:5432"
    volumes:
      - auth-db:/data/db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  auth-db: