# user-service

version: '3.8'

services:
  user-service:
    image: node:19.0.0-alpine
    container_name: user-service
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    env_file:
      - .user-service.env
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node
      - ../libs:/home/node/libs

  user-service-db:
    image: postgres:15-alpine3.16
    container_name: user-service-db
    restart: always
    env_file:
      - .user-service.env
    environment:
      POSTGRES_PASSWORD: ${USER_SERVICE_PASSWORD}
      POSTGRES_HOST: ${USER_SERVICE_HOST}
      POSTGRES_PORT: ${USER_SERVICE_PORT}
      POSTGRES_USER: ${USER_SERVICE_USER}
      POSTGRES_DB: ${USER_SERVICE_DB}
    ports:
      - "5433:5432"
    volumes:
      - user-db:/data/db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  user-db:

networks:
  default:
    name: microservices-network
    external: true