version: '3.8'

services:
  user-service:
    image: node:19.0.0-alpine
    container_name: service
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node

  user-service-db:
    image: postgres:15-alpine3.16
    container_name: auth-service-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/data/db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db: