# gateway-service

version: '3.8'

services:
  gateway-service:
    image: node:19.0.0-alpine
    container_name: gateway-service
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
#    env_file:
#      - .env
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node
      - ../libs:/home/node/libs

networks:
  default:
    name: microservices-network